# Generated by Django 5.0.7 on 2024-07-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCApp', '0002_alter_cartproduct_color_size_and_more'),
        ('store', '0006_remove_colorsize_color_remove_colorsize_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorSize',
        ),
    ]
