# Generated by Django 5.0.6 on 2024-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_remove_myuser_groups_remove_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(db_table='permission_users', related_name='users', to='superuser.role'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
