# Generated by Django 5.0.6 on 2024-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_role_myuser_role_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(db_table='user_role', related_name='users', to='superuser.role'),
        ),
    ]
