# Generated by Django 5.0.6 on 2024-07-06 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.ManyToManyField(db_table='user_role', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
