# Generated by Django 5.0.7 on 2024-07-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
